name: '${pluginName}'
version: '${version}'
main: org.yuemi.mmomobs.plugin.MmoMobsPlugin
authors: [${authors}]
api-version: '${apiVersion}'

softdepend: [
  YueMiLibs,
  PlaceholderAPI
]

commands:
  mmomobs:
    description: "Main command for MC-MMO-Mobs"
    aliases: [mobs]
    permission: mmomobs.admin
